---
title: "Crop Yield "
author: "Luis R. Alvarez"
date: "`r Sys.Date()`"
output: pdt2_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

# Data set title: Precision Agriculture Yield Monitoring in Row Crop Agriculture at the Kellogg Biological Station, Hickory Corners, MI  (1996 to 2013).
# Data set creator:  G. Robertson - Michigan State University 
# Metadata Link: https://portal.lternet.edu/nis/metadataviewer?packageid=knb-lter-kbs.37.23

```{r}
library(dplyr)
library(lubridate)
library(tidyverse)
library(corrplot)
library(car)
library(stats)
```

```{r Download Data}
# pluck data from url
url_download  <- "https://pasta.lternet.edu/package/data/eml/knb-lter-kbs/37/23/610992a4f20d12c39908281b822291a6" 
# temporary gadget
file_download <- tempfile()
#  ingest file with curl command, check for NAs, and download
try(download.file(url_download, file_download,method="curl"))
if (is.na(file.size(file_download))) download.file(url_download,file_download,method="auto")

# read file and instantiate local data frame 
  dt1 <-read.csv(file_download,header=F, skip=34, sep=",",quot='"', 
                 col.names=c(
                    "longitude",     
                    "latitude",     
                    "crop_flow_lb_s",     
                    "datetime",     
                    "duration",     
                    "distance_in",     
                    "swth_wdth_in",     
                    "moisture",     
                    "status",     
                    "pass_num",     
                    "serial_number",     
                    "field",     
                    "dataset",     
                    "product",     
                    "elevation_ft"), check.names=TRUE)
# close reading of file               
unlink(file_download)


```

```{r subset columns}
# read column names and data types
data_types <- sapply(dt1,class)
data_types

# subset columns by reviewing merit of each
dt2 <- select(dt1,longitude, latitude, crop_flow_lb_s, datetime, duration, 
              distance_in,swth_wdth_in, moisture, status, pass_num, serial_number, field,elevation_ft)
```

```{r subset columns}
data_types2 <- sapply(dt2,class)
data_types2
```

```{r Subset Variables}
# Rename variables as factors
variables_to_convert <- c("swth_wdth_in",
                          "serial_number",
                          "field",
                          "pass_num",
                          "duration",
                          "status")

# Using lapply for concise conversion
dt2[variables_to_convert] <- lapply(dt2[variables_to_convert], as.factor)
data_types2 <- sapply(dt2,class)

# rename variable as logical
#dt2$status <- lapply(dt2$status, as.logical)


# Convert the datetime column to a POSIXct object ((in lubridate))
dt2$datetime_column <- ymd_hms(dt2$datetime)

# Extract year, month, day, and time components
dt2$year <- year(dt2$datetime_column)
dt2$month <- month(dt2$datetime_column)
dt2$day <- day(dt2$datetime_column)
dt2$time <- hms::as_hms(dt2$datetime_column) # convert character dtype to hours min seconds.
dt2$time <- scale(dt2$time) # transform variable for ease of use

# Drop date_time and original datetime columns
dt2[c("datetime", "datetime_column")] <- NULL

```

```{r dentisty plots}
#Get density plots for all variables
dt2 %>% keep(is.numeric) %>% gather() %>% ggplot(aes(value)) + facet_wrap(~ key, scales = "free")+geom_density(color="blue", fill='green')

```

```{r NA}
# check for NA
missing_values_summary <- sapply(dt2, function(x) sum(is.na(x)))
print(missing_values_summary)

# about 30K rows only missing status
na_status <- sum(is.na(dt2$status))
# impute value 3 for missing implement status. Three represents status unknown
dt2$status <- ifelse(is.na(dt2$status), 3, dt2$status)

# check for NA
missing_values_summary <- sapply(dt2, function(x) sum(is.na(x)))
print(missing_values_summary)
```


```{r}
# Numeric variables
num_vars <- dt2[,sapply(dt2,is.numeric)]

factors_ <- lapply(dt2[, variables_to_convert], unique)
factors_

# Matrix
mat<-cor(num_vars)
# Fancy graph for correlation matrix
corrplot(mat, method = "ellipse") # visualize collinearity

```

```{r}
# EDA
# average moisture by year, month for each field = bar graphs
# average crop flow for each field by year
# plot moisture for fields by year
```

```{r Base}
# # TODO: random sample of 1000 points hold out test set
# base model
# linear regression
start_time <- Sys.time()
lm_mod1 <- glm(crop_flow_lb_s ~ ., data = dt2)
influence_values <- influence.measures(lm_mod1)


end_time <- Sys.time()
elapsed_time <- end_time - start_time
print(elapsed_time)

```

```{r save base model}
# Parse model
glmparsed <- parse_model(model)

```


```{r}
# Extract residuals and leverage values
residuals <- influence_values$residuals
leverage <- influence_values$hat

# Plot residuals vs leverage
plot(leverage, residuals, main = "Residuals vs Leverage", 
     xlab = "Leverage", ylab = "Residuals", pch = 19)

# Add a reference line for identifying influential points
abline(h = 0, col = "red", lty = 2)
# Extract residuals and leverage values
residuals <- influence_values$residuals
leverage <- influence_values$hat

# Plot residuals vs leverage
plot(leverage, residuals, main = "Residuals vs Leverage", 
     xlab = "Leverage", ylab = "Residuals", pch = 19)

# Add a reference line for identifying influential points
abline(h = 0, col = "red", lty = 2)

```

